### ISSUE TITLE
jboss 4.2.3, that runs on JDK6 does not load stripe-java-5.35.1.jar

### ISSUE THREAD

**Issue by marinalan** [stripe/stripe-java#502] opened 2018-05-04 09:28 UTC
I am dealing with legacy old project that runs on JDK6 within jboss4.2.3. Unfortunately, I get exception
`java.lang.NoClassDefFoundError: com/stripe/Stripe`
when attempt to do in servlet: `Stripe.apiKey = secretKey;`
All that i want is to run few lines to create Charge:

```java
Map<String, Object> chargeParams = new HashMap<String, Object>();
       chargeParams.put("amount", new Integer(charge_info.get("amount").getAsInt()));
       chargeParams.put("currency", charge_info.get("currency").getAsString());
       chargeParams.put("source", charge_info.get("token").getAsString());
       chargeParams.put("description", sb.toString());
       Charge charge = Charge.create(chargeParams);
```

I just want to pass token.id from checkout.js popup, amount, currency. What can I do? Which is the latest version of stripe-java still compatible with JDK6 and and which supports Charge.create using token, generated by checkout.js javascript code?

Or: How to recompile your library for JDK6?

**Comment by ob-stripe** [comment] 2018-05-04 09:56
Hi @marinalan. Unfortunately, Stripe's Java library no longer supports Java 6, as you can see in the [requirements](https://github.com/stripe/stripe-java#requirements). The main reason is that Java 6 does not support TLS 1.2, which is now required to establish connections to Stripe's API (cf. [this blog post](https://stripe.com/blog/upgrading-tls)).

You must use Java 7 or or more recent in order to use Stripe in your project.

Closing this issue as this is not a bug with the library. If you have further questions, please reach out to support at https://support.stripe.com/email.

**Closed by ob-stripe** 2018-05-04 09:56 UTC
