### ISSUE TITLE
Losing existing metadata when updating issuing cardholder

### ISSUE THREAD

**Issue by totof3110** [stripe/stripe-java#1110] opened 2020-09-24 22:07 UTC
I am not sure whether this is a SDK issue or a backend issue, but updating the issuing cardholder metadata works in a different way from the rest of the metadata-carrying Stripe objects. When adding a metadata entry, all existing entries seem to be cleared, whereas for other entity types, the metadata not mentioned in the update is preserved. This is potentially causing data loss.

You can reproduce the issue the following way:
```java
Cardholder cardholder = Cardholder.retrieve(cardholderId, requestOptions);

System.out.println("Initial: " + cardholder.getMetadata());

cardholder = cardholder.update(CardholderUpdateParams.builder()
		.putMetadata("foo", "bar")
		.build(), requestOptions);

System.out.println("After first update: " + cardholder.getMetadata());

cardholder = cardholder.update(CardholderUpdateParams.builder()
		.putMetadata("baz", "qux")
		.build(), requestOptions);

System.out.println("After second update: " + cardholder.getMetadata());
```
which gives the following output:
```
Initial: {}
After first update: {foo=bar}
After second update: {baz=qux}
```
(the 2nd update cleared the `foo` metadata even though it wasn't supposed to)

**Comment by totof3110** [comment] 2020-09-24 22:12
Another strange behavior of the cardholder metadata update is that it's not possible to remove an entry by setting it as null:
```java
Cardholder cardholder = Cardholder.retrieve(cardholderId, requestOptions);
cardholder = cardholder.update(CardholderUpdateParams.builder()
		.putMetadata("foo", "bar")
		.build(), requestOptions);

System.out.println("After first update: " + cardholder.getMetadata());

cardholder = cardholder.update(CardholderUpdateParams.builder()
		.putMetadata("foo", null)
		.build(), requestOptions);

System.out.println("After second update: " + cardholder.getMetadata());
```
outputs:
```
After first update: {foo=bar}
After second update: {foo=}
```
The second update seems to leave the `foo` key in the metadata with an empty string value instead of removing it completely (behavior for the other entities), which the wed UI has trouble with BTW:
![image](https://user-images.githubusercontent.com/294891/94205506-48da0600-fe78-11ea-808c-69c285dc1571.png)

**Comment by remi-stripe** [comment] 2020-09-24 22:19
@totof3110 Thanks for reaching out. This is a bug in the API itself and not stripe-java unfortunately. I'm going to flag internally so that we can get this fix and confirm it works consistently across all other Issuing endpoints. Thanks a lot for the detailed reproduction steps as it made my life a lot easier :)

I'm going to close this issue since it's an API bug but you can reach out to our support team here https://support.stripe.com/contact so that they can keep you updated on a fix

**Closed by remi-stripe** 2020-09-24 22:19 UTC

**Comment by totof3110** [comment] 2020-09-24 22:33
Thanks @remi-stripe. I had a hunch that this was an API bug. Thanks for confirming. I'll reach out to support.

**Comment by remi-stripe** [comment] 2020-09-28 15:26
Circling back on this, we deployed a fix!

**Comment by totof3110** [comment] 2020-09-28 16:20
Thanks for the quick turnaround @remi-stripe ! I tried it out and all issues are resolved.
