### ISSUE TITLE
Transfer's date field return as a double instead of a long

### ISSUE THREAD

**Issue by fclairamb** [stripe/stripe-java#373] opened 2017-05-04 03:03 UTC
Our Stripe integration started to fail (at least in TEST so far).

From the Stripe API, while performing a transfer request, the `date` property of the `Transfer` entity is returned with a double (nanosecond precision epoch time) instead of a long (second precision epoch time). And the java-library fails on this `date` property with this error:

```
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected a long but was 1493864869.1529725 at line 23 column 29
```

The go library seems unaffected as this `date` property is ignored (only the `created` one is used).

The `Transfer` object we received from the Stripe API and we are trying to deserialize is:
```
{
  "id": "tr_1AFZXILTCGVKWflt1klSzzVY",
  "object": "transfer",
  "amount": 500,
  "amount_reversed": 0,
  "balance_transaction": "txn_1AFZXILTCGVKWfltqmRzMsbV",
  "created": 1493864264,
  "currency": "usd",
  "destination": "acct_1AFYEfGoeq1v1idM",
  "destination_payment": "py_1AFZXIGoeq1v1idMNnWmywHg",
  "livemode": false,
  "metadata": {},
  "reversals": {
    "object": "list",
    "data": [],
    "has_more": false,
    "total_count": 0,
    "url": "/v1/transfers/tr_1AFZXILTCGVKWflt1klSzzVY/reversals"
  },
  "reversed": false,
  "source_type": "card",
  "transfer_group": "group_ch_1AFZXILTCGVKWflt1Xa81T4T",
  "date": 1493864264.4292502,
  "status": "paid",
  "type": "stripe_account",
  "method": "standard",
  "description": null,
  "failure_message": null,
  "failure_code": null,
  "statement_descriptor": null,
  "recipient": null,
  "source_transaction": "ch_1AFZXILTCGVKWflt1Xa81T4T",
  "application_fee": null
}
```

Note we are on the version `2016-07-06` of the API.

**Comment by ob-stripe** [comment] 2017-05-04 07:50
Hey @fclairamb, thanks for reporting this! We're investigating the issue. I'll reply here when I know more.

**Comment by ob-stripe** [comment] 2017-05-04 08:23
@fclairamb This problem was caused by a bug on the API's end, where we mistakenly started returning floats instead of ints for the `date` property on internal transfers (i.e. transfers between Stripe accounts, not payouts from a Stripe account to a bank account).

The issue is now fixed. Sorry for the inconvenience! I'm going to close the issue as this was a problem with the API and not with the Java library, but feel free to reach out to us at https://support.stripe.com/email if you have any more questions.

**Closed by ob-stripe** 2017-05-04 08:23 UTC
