### ISSUE TITLE
PaymentIntent.create NoSuchMethodError

### ISSUE THREAD

**Issue by VictorDCosta** [stripe/stripe-java#816] opened 2019-08-01 15:38 UTC
Version: 10.12.1
My code attempts:

```java
PaymentIntentCreateParams.Builder params = PaymentIntentCreateParams.builder();
params.setAmount(1099L);
params.setCurrency("eur");
params.setDescription(purchaseDescription);
params.setConfirm(true);
params.setConfirmationMethod(PaymentIntentCreateParams.ConfirmationMethod.MANUAL);
params.setPaymentMethod(paymentMethodId);
params.setCustomer(customerStripeToken);
params.setSetupFutureUsage(PaymentIntentCreateParams.SetupFutureUsage.ON_SESSION);
PaymentIntent paymentIntent = PaymentIntent.create(params.build());
```

And:

```java
Map<String, Object> params = new HashMap<>();
params.put("amount", amount.multiply(new BigDecimal(100)).setScale(0, RoundingMode.HALF_UP).intValue());
params.put("currency", "eur");
params.put("description", purchaseDescription);
params.put("confirm", true);
params.put("confirmation_method", "manual");
params.put("payment_method", paymentMethodId);
params.put("customer", customerStripeToken);
params.put("setup_future_usage", "on_session");
PaymentIntent paymentIntent = PaymentIntent.create(params);
```

Result:

```
Caused by: java.lang.NoSuchMethodError: com.stripe.net.StripeResponseGetter.request(Lcom/stripe/net/ApiResource$RequestMethod;Ljava/lang/String;Ljava/util/Map;Ljava/lang/Class;Lcom/stripe/net/ApiResource$RequestType;Lcom/stripe/net/RequestOptions;)Ljava/lang/Object;
	at com.stripe.net.ApiResource.request(ApiResource.java:228)
	at com.stripe.net.ApiResource.request(ApiResource.java:218)
	at com.stripe.model.PaymentIntent.create(PaymentIntent.java:489)
	at com.stripe.model.PaymentIntent.create(PaymentIntent.java:470)
	at ptvoid.goin.stripe.boundary.StripeService.createCharge(StripeService.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:437)
	at org.jboss.as.weld.ejb.DelegatingInterceptorInvocationContext.proceed(DelegatingInterceptorInvocationContext.java:87)
	at org.jboss.weld.interceptor.proxy.WeldInvocationContext.interceptorChainCompleted(WeldInvocationContext.java:98)
	at org.jboss.weld.interceptor.proxy.WeldInvocationContext.proceed(WeldInvocationContext.java:117)
	at org.hibernate.validator.internal.cdi.interceptor.ValidationInterceptor.validateMethodInvocation(ValidationInterceptor.java:78)
	at sun.reflect.GeneratedMethodAccessor566.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:74)
	at org.jboss.weld.interceptor.proxy.WeldInvocationContext.invokeNext(WeldInvocationContext.java:83)
	at org.jboss.weld.interceptor.proxy.WeldInvocationContext.proceed(WeldInvocationContext.java:115)
	at org.jboss.weld.bean.InterceptorImpl.intercept(InterceptorImpl.java:108)
	at org.jboss.as.weld.ejb.DelegatingInterceptorInvocationContext.proceed(DelegatingInterceptorInvocationContext.java:77)
	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.delegateInterception(Jsr299BindingsInterceptor.java:68)
	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:80)
	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:93)
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:437)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
	at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:83)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:254)
	... 373 more
```

**Comment by ob-stripe** [comment] 2019-08-02 01:55
Hi @VictorDCosta. This is almost certainly not an issue with the stripe-java library. `NoSuchMethodError` exceptions are usually caused by using different versions of a library at compile time and at runtime.

Here's a blog post that explains this in more details: https://reflectoring.io/nosuchmethod/. I recommend you check your build and execution environments to ensure that you're using the same version of stripe-java in both.

Closing the issue since I'm fairly certain this is not a bug in stripe-java, but feel free to reply.

**Closed by ob-stripe** 2019-08-02 01:55 UTC

**Comment by VictorDCosta** [comment] 2019-08-02 08:51
Thanks for the input, it was exactly that.
