### ISSUE TITLE
getResponseGetter() not set on account.capabilities()

### ISSUE THREAD

**Issue by summith91** [stripe/stripe-java#1705] opened 2023-12-08 21:09 UTC
### Describe the bug

Accessing Account Capabilities leading to exception
```
java.lang.IllegalStateException: The StripeResponseGetter has not been set on this resource. This should not happen and is likely a bug in the Stripe Java library. Please open a github issue on https://github.com/stripe/stripe-java or contact Stripe Support at https://support.stripe.com/contact/
	at com.stripe.net.ApiResource.getResponseGetter(ApiResource.java:35)
	at com.stripe.model.Account.capabilities(Account.java:188)
	at com.stripe.model.Account.capabilities(Account.java:169)
```

### To Reproduce

Code 
```
Account account = stripeApiProxy.retrieveAccount(stripeAccountId);
boolean isCardPaymentEnabled = account.capabilities().retrieve("card_payments").getStatus().equals("active");
```

Testing this leads to exception
using mockStripeApiProxy to call
`when(mockApiProxy.retrieveAccount(stripeAccountId)).thenReturn(StripeAccountMocks.TEST_STRIPE_ACCOUNT);`

```
TEST_STRIPE_ACCOUNT = new Account();
    TEST_STRIPE_ACCOUNT.setId("acct_1GJ2Z2KZ4Z4Z4Z4Z");

    final Account.Capabilities capabilities = new Account.Capabilities();
    capabilities.setCardPayments("active");
    capabilities.setTransfers("active");
    capabilities.setAfterpayClearpayPayments("active");
    TEST_STRIPE_ACCOUNT.setCapabilities(capabilities);
    TEST_STRIPE_ACCOUNT.setChargesEnabled(true);
    TEST_STRIPE_ACCOUNT.setPayoutsEnabled(true);
```

And so on. 

### Expected behavior

I'd get Capabilities object and use status field to check further

### OS

macOS Sonoma 14.1.2

### Java version

Java 11

### stripe-java version

v23.5.0

### API version

2023-08-16

**Comment by richardm-stripe** [comment] 2023-12-11 21:11
Hello @summith91, thanks for writing in. I think your issue is related to how you are calling constructors for stripe resources directly (like `new Account()`). I was able to reproduce the error like this:
```java
Stripe.apiKey = "sk_test_xyz";
Account account = new Account();
account.setId("acct_123");
account.update(Map.of());
```
In [v23.0.0](https://github.com/stripe/stripe-java/releases/tag/v23.0.0), when we introduced `StripeClient` we made some changes to the implementation that mean constructing a Stripe resource directly and then trying to make a request from the instance will fail.



(Before v23 there was really only one way to request a resource, via the

I would try and write your tests to avoid constructing a stripe object directly. One option is, instead of
```
Account account = new Account();
account.setId("acct_123");
```
you can do
```
StripeObject.deserializeStripeObject("{\"object\": \"account\", \"id\": \"acct_123\"}");
```


To try and explain this behavior, as of v23
```
StripeClient stripe = new StripeClient("sk_test_1");
Stripe.api_key = "sk_test_2";
Account account1 = stripe.accounts().retrieve("acct_xyz"); 
Account account2 = Account.retrieve("acct_xyz");
Account account3 = new Account();
account3.setId("acct_xyz");

account1.update(...);
account1.update(...);

**Comment by richardm-stripe** [comment] 2023-12-11 21:30
Hello @summith91, thanks for writing in. I think your issue is related to how you are calling constructors for stripe resources directly (like `new Account()`). I was able to reproduce the error like this:
```java
Stripe.apiKey = "sk_test_xyz";
Account account = new Account();
account.setId("acct_123");
account.update(Map.of());
```

Despite the error message, I'm not sure this represents a bug that we intend to fix.

### Recommendation
I would try and write your tests to avoid constructing a stripe object directly. One option is, instead of
```java
Account account = new Account();
account.setId("acct_123");
```

you can do
```java
StripeObject.deserializeStripeObject("{\"object\": \"account\", \"id\": \"acct_123\"}");
```

Another (worse) option would be
```java
Account account = new Account();
account.setResponseGetter(ApiResource.getGlobalResponseGetter());
```

### Rationale
To offer some explanation for the new behavior: 
In [v23.0.0](https://github.com/stripe/stripe-java/releases/tag/v23.0.0), we introduced `StripeClient`, a way for you to configure different instances of Stripe instead of having to use/rely on a single, global client. That means, there's now two different ways to e.g. retrieve a Stripe Account and we've tried to be conservative and avoid making assumptions about which is intended. 

```java
StripeClient stripe = new StripeClient("sk_test_1");
Stripe.api_key = "sk_test_2";

// This is new in v23
Account account1 = stripe.accounts().retrieve("acct_xyz"); 

// This is the old way
Account account2 = Account.retrieve("acct_xyz");

// This is what you may have been doing in your tests.
Account account3 = new Account(); 
account3.setId("acct_xyz");

account1.update(...); // Should use "sk_test_1" from the StripeClient
account2.update(...); // Should use "sk_test_2" from the global client
account3.update(...): // Should use ???. We've chosen to throw an exception here instead of assuming the global client.
```

### Discussion

I hope the recommendations work for you and resolve your issue. Sorry for the misleading error message. We're open to discussion about the behavior change we made here, too. If avoiding direct construction of Stripe resources doesn't sit right with you, I'd be interested to learn more about your testing approach and why you are calling resource constructors directly / what you are trying to exercise with your test.

**Comment by richardm-stripe** [comment] 2023-12-16 00:23
Preemptively closing as I believe the question has been answered, but feel free to re-open and discuss if you wish!

**Closed by richardm-stripe** 2023-12-16 00:23 UTC
Labels: bug
