### ISSUE TITLE
The Token class does not handle the bank_account property

### ISSUE THREAD

**Issue by remistr** [stripe/stripe-java#151] opened 2015-03-20 23:27 UTC
At the moment the `Token` class only expects a `Card` object back and not a `BankAccount` which prevents you from accessing the bank account's properties until you add it to a recipient.

**Comment by mmcgrana** [comment] 2015-08-31 18:53
I believe this is a duplicate of #212 which is fixed in a release going out now. 

@remistr if this is not a dup please just reopen and let me know.

**Closed by mmcgrana** 2015-08-31 18:53 UTC
