### ISSUE TITLE
[Enhancement] Ability to set customer invoice email and cc 

### ISSUE THREAD

**Issue by rferreira** [stripe/stripe-java#797] opened 2019-06-30 01:54 UTC
Enhancement
The goal here is to allow the ability to set a customer's invoice preferences using the java client much like we can do using the web ui: 

<img width="479" alt="image" src="https://user-images.githubusercontent.com/36054/60391229-703bfa80-9a9e-11e9-8c83-9634942fc9a5.png">

**Comment by karlr-stripe** [comment] 2019-07-01 11:28
Hi @rferreira — currently it's not possible to set this field via the API itself, so it's not something that can be added to stripe-java : the underlying API doesn't have a way to set this field. See this similar discussion for stripe-dotnet : https://github.com/stripe/stripe-dotnet/issues/1599 If it becomes possible to edit this field in the API in future, stripe-java will be updated to support that!

I'm closing this issue as it's not a bug with stripe-java for the moment.

**Closed by karlr-stripe** 2019-07-01 11:28 UTC
