### ISSUE TITLE
Explicit GSON dependency is required for deserializing StripeObject

### ISSUE THREAD

**Issue by ved-asole** [stripe/stripe-java#1928] opened 2024-11-30 08:09 UTC
### Describe the bug

When using the below code, it is not able to find JsonObject in the project and the builds are failing :

```java
StripeObject stripeObject = StripeObject.deserializeStripeObject(
                    event.getData().getObject().toJson(),
                    event.getData().getObject().getClass(),
                    new LiveStripeResponseGetter()
            );
``` 

### Full Code :

```java
 @PostMapping("/webhook/stripe")
    public void handleStripeEvents(
            @RequestBody String payload,
            @RequestHeader("Stripe-Signature") String sigHeader
    ) {
        log.debug("Webhook received with sigHeader: {}", sigHeader);
        try {
            // Verify the signature
            Webhook.Signature.verifyHeader(payload, sigHeader, endpointSecret, 300L);
            log.debug("Webhook received and verified header: {}", sigHeader);

            Event event = Webhook.constructEvent(payload, sigHeader, endpointSecret);
            log.info("event_id : {}, event_type: {}", event.getId(), event.getType());

            StripeObject stripeObject = StripeObject.deserializeStripeObject(
                    event.getData().getObject().toJson(),
                    event.getData().getObject().getClass(),
                    new LiveStripeResponseGetter()
            );

            paymentService.handleStripeEvents(stripeObject);
            log.info("Event processed successfully: {}", event.getId());

        } catch (SignatureVerificationException e) {
            // Invalid signature
            log.error("Event signature verification failed: sigHeader[{}]", sigHeader, e);
            throw new APIException("Invalid Event- signature verification failed", HttpStatus.BAD_REQUEST);
        } catch (Exception e) {
            // Other exceptions
            log.error("Error processing event: {}", e.getMessage(), e);
            throw new APIException("Error processing event", HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }
``` 

### Workaround is there but solution is required to be updated in API :

Add below dependency in the project to resolve the issue :

```java
      <!-- https://mvnrepository.com/artifact/com.google.code.gson/gson -->
      <dependency>
          <groupId>com.google.code.gson</groupId>
          <artifactId>gson</artifactId>
          <version>2.10.1</version>
      </dependency>
```

### To Reproduce

Use the below controller code with Spring Boot app to reproduce the issue :

```java
 @PostMapping("/webhook/stripe")
    public void handleStripeEvents(
            @RequestBody String payload,
            @RequestHeader("Stripe-Signature") String sigHeader
    ) {
        log.debug("Webhook received with sigHeader: {}", sigHeader);
        try {
            // Verify the signature
            Webhook.Signature.verifyHeader(payload, sigHeader, endpointSecret, 300L);
            log.debug("Webhook received and verified header: {}", sigHeader);

            Event event = Webhook.constructEvent(payload, sigHeader, endpointSecret);
            log.info("event_id : {}, event_type: {}", event.getId(), event.getType());

            StripeObject stripeObject = StripeObject.deserializeStripeObject(
                    event.getData().getObject().toJson(),
                    event.getData().getObject().getClass(),
                    new LiveStripeResponseGetter()
            );

            paymentService.handleStripeEvents(stripeObject);
            log.info("Event processed successfully: {}", event.getId());

        } catch (SignatureVerificationException e) {
            // Invalid signature
            log.error("Event signature verification failed: sigHeader[{}]", sigHeader, e);
            throw new APIException("Invalid Event- signature verification failed", HttpStatus.BAD_REQUEST);
        } catch (Exception e) {
            // Other exceptions
            log.error("Error processing event: {}", e.getMessage(), e);
            throw new APIException("Error processing event", HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }
``` 

### Expected behavior

Expected behavior is that the explicit adding of GSON dependency should not be required after using Stripe SDK

### Code snippets

```Java
@PostMapping("/webhook/stripe")
    public void handleStripeEvents(
            @RequestBody String payload,
            @RequestHeader("Stripe-Signature") String sigHeader
    ) {
        log.debug("Webhook received with sigHeader: {}", sigHeader);
        try {
            // Verify the signature
            Webhook.Signature.verifyHeader(payload, sigHeader, endpointSecret, 300L);
            log.debug("Webhook received and verified header: {}", sigHeader);

            Event event = Webhook.constructEvent(payload, sigHeader, endpointSecret);
            log.info("event_id : {}, event_type: {}", event.getId(), event.getType());

            StripeObject stripeObject = StripeObject.deserializeStripeObject(
                    event.getData().getObject().toJson(),
                    event.getData().getObject().getClass(),
                    new LiveStripeResponseGetter()
            );

            paymentService.handleStripeEvents(stripeObject);
            log.info("Event processed successfully: {}", event.getId());

        } catch (SignatureVerificationException e) {
            // Invalid signature
            log.error("Event signature verification failed: sigHeader[{}]", sigHeader, e);
            throw new APIException("Invalid Event- signature verification failed", HttpStatus.BAD_REQUEST);
        } catch (Exception e) {
            // Other exceptions
            log.error("Error processing event: {}", e.getMessage(), e);
            throw new APIException("Error processing event", HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }
```

### OS

Ubuntu

### Java version

Java 17

### stripe-java version

v25.13.0

### API version

25.13.0

**Comment by seanzhang-stripe** [comment] 2024-12-01 05:00
Hi @ved-asole [gson](https://github.com/stripe/stripe-java/blob/master/build.gradle#L90) is one of the dependencies that `stripe-java` uses. If you are using [Maven or Gradle](https://github.com/stripe/stripe-java/tree/master?tab=readme-ov-file#installation), `gson` will be automatically downloaded when you include `stripe-java` in your project. 

Can you share the detailed error stack trace, and also tell me a bit more about how you include `stripe-java` in your project?

**Comment by ved-asole** [comment] 2024-12-04 05:45
I'm using the below maven dependency :

```java
 <dependency>
      <groupId>com.stripe</groupId>
      <artifactId>stripe-java</artifactId>
      <version>25.13.0</version>
</dependency>
```

### Error : cannot access com.google.gson.JsonObject

### Code :

```java
StripeObject stripeObject = StripeObject.deserializeStripeObject(
                    event.getData().getObject().toJson(),
                    event.getData().getObject().getClass(),
                    new LiveStripeResponseGetter()
            );
``` 

![image](https://github.com/user-attachments/assets/57738f05-f438-4251-a0fa-31258223b0ea)

**Comment by ved-asole** [comment] 2024-12-04 05:46
The issue resolves after adding the below dependency :

```java
<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.10.1</version>
</dependency>
```

**Comment by seanzhang-stripe** [comment] 2024-12-04 07:48
Can you run `mvn dependency:tree` in your project and see if `com.google.code.gson:gson` is included in `com.stripe:stripe-java'`s dependency list?

**Comment by ved-asole** [comment] 2024-12-05 09:20
Please find below the output :

```java
[INFO] com.vedasole:ekart-ecommerce-backend:jar:0.0.1-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter-data-jpa:jar:2.7.14:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-aop:jar:2.7.14:compile
[INFO] |  |  \- org.aspectj:aspectjweaver:jar:1.9.7:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-jdbc:jar:2.7.14:compile
[INFO] |  |  +- com.zaxxer:HikariCP:jar:4.0.3:compile
[INFO] |  |  \- org.springframework:spring-jdbc:jar:5.3.29:compile
[INFO] |  +- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile
[INFO] |  +- jakarta.persistence:jakarta.persistence-api:jar:2.2.3:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:5.6.15.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.4.3.Final:compile
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.12.23:compile
[INFO] |  |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  +- org.jboss:jandex:jar:2.4.2.Final:compile
[INFO] |  |  +- org.hibernate.common:hibernate-commons-annotations:jar:5.1.2.Final:compile
[INFO] |  |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.8:compile
[INFO] |  |     +- org.glassfish.jaxb:txw2:jar:2.3.8:compile
[INFO] |  |     \- com.sun.istack:istack-commons-runtime:jar:3.0.12:compile
[INFO] |  +- org.springframework.data:spring-data-jpa:jar:2.7.14:compile
[INFO] |  |  +- org.springframework.data:spring-data-commons:jar:2.7.14:compile
[INFO] |  |  +- org.springframework:spring-orm:jar:5.3.29:compile
[INFO] |  |  +- org.springframework:spring-context:jar:5.3.29:compile
[INFO] |  |  +- org.springframework:spring-tx:jar:5.3.29:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:5.3.29:compile
[INFO] |  \- org.springframework:spring-aspects:jar:5.3.29:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.7.14:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.7.14:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.7.14:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.17.2:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.17.2:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.36:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.30:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.7.14:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.13.5:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.5:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.13.5:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.7.14:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.78:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.78:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.29:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.3.29:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.3.29:compile
[INFO] +- org.springframework.boot:spring-boot-starter-validation:jar:2.7.14:compile
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.78:compile
[INFO] |  \- org.hibernate.validator:hibernate-validator:jar:6.2.5.Final:compile
[INFO] |     \- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] +- org.springframework.boot:spring-boot-starter-data-redis:jar:2.7.14:compile
[INFO] |  +- org.springframework.data:spring-data-redis:jar:2.7.14:compile
[INFO] |  |  +- org.springframework.data:spring-data-keyvalue:jar:2.7.14:compile
[INFO] |  |  \- org.springframework:spring-oxm:jar:5.3.29:compile
[INFO] |  \- io.lettuce:lettuce-core:jar:6.1.10.RELEASE:compile
[INFO] |     +- io.netty:netty-common:jar:4.1.94.Final:compile
[INFO] |     +- io.netty:netty-handler:jar:4.1.94.Final:compile
[INFO] |     |  +- io.netty:netty-resolver:jar:4.1.94.Final:compile
[INFO] |     |  +- io.netty:netty-buffer:jar:4.1.94.Final:compile
[INFO] |     |  +- io.netty:netty-transport-native-unix-common:jar:4.1.94.Final:compile
[INFO] |     |  \- io.netty:netty-codec:jar:4.1.94.Final:compile
[INFO] |     +- io.netty:netty-transport:jar:4.1.94.Final:compile
[INFO] |     \- io.projectreactor:reactor-core:jar:3.4.31:compile
[INFO] |        \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] +- org.springframework.boot:spring-boot-starter-cache:jar:2.7.14:compile
[INFO] |  \- org.springframework:spring-context-support:jar:5.3.29:compile
[INFO] +- org.modelmapper:modelmapper:jar:3.1.0:compile
[INFO] +- com.google.code.gson:gson:jar:2.10.1:compile
[INFO] +- org.springframework.boot:spring-boot-devtools:jar:2.7.14:runtime
[INFO] |  +- org.springframework.boot:spring-boot:jar:2.7.14:compile
[INFO] |  \- org.springframework.boot:spring-boot-autoconfigure:jar:2.7.14:compile
[INFO] +- com.h2database:h2:jar:2.2.220:runtime
[INFO] +- org.postgresql:postgresql:jar:42.7.2:runtime
[INFO] |  \- org.checkerframework:checker-qual:jar:3.42.0:runtime
[INFO] +- org.projectlombok:lombok:jar:1.18.30:compile
[INFO] +- io.springfox:springfox-boot-starter:jar:3.0.0:compile
[INFO] |  +- io.springfox:springfox-oas:jar:3.0.0:compile
[INFO] |  |  +- io.swagger.core.v3:swagger-annotations:jar:2.1.2:compile
[INFO] |  |  +- io.swagger.core.v3:swagger-models:jar:2.1.2:compile
[INFO] |  |  +- io.springfox:springfox-spi:jar:3.0.0:compile
[INFO] |  |  +- io.springfox:springfox-schema:jar:3.0.0:compile
[INFO] |  |  +- io.springfox:springfox-core:jar:3.0.0:compile
[INFO] |  |  +- io.springfox:springfox-spring-web:jar:3.0.0:compile
[INFO] |  |  |  \- io.github.classgraph:classgraph:jar:4.8.83:compile
[INFO] |  |  +- io.springfox:springfox-spring-webmvc:jar:3.0.0:compile
[INFO] |  |  +- io.springfox:springfox-spring-webflux:jar:3.0.0:compile
[INFO] |  |  +- io.springfox:springfox-swagger-common:jar:3.0.0:compile
[INFO] |  |  \- org.mapstruct:mapstruct:jar:1.3.1.Final:runtime
[INFO] |  +- io.springfox:springfox-data-rest:jar:3.0.0:compile
[INFO] |  +- io.springfox:springfox-bean-validators:jar:3.0.0:compile
[INFO] |  +- io.springfox:springfox-swagger2:jar:3.0.0:compile
[INFO] |  |  +- io.swagger:swagger-annotations:jar:1.5.20:compile
[INFO] |  |  \- io.swagger:swagger-models:jar:1.5.20:compile
[INFO] |  +- io.springfox:springfox-swagger-ui:jar:3.0.0:compile
[INFO] |  +- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.36:compile
[INFO] |  +- org.springframework.plugin:spring-plugin-core:jar:2.0.0.RELEASE:compile
[INFO] |  \- org.springframework.plugin:spring-plugin-metadata:jar:2.0.0.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-hateoas:jar:2.7.14:compile
[INFO] |  \- org.springframework.hateoas:spring-hateoas:jar:1.5.5:compile
[INFO] +- io.jsonwebtoken:jjwt-api:jar:0.11.5:compile
[INFO] +- io.jsonwebtoken:jjwt-impl:jar:0.11.5:runtime
[INFO] +- io.jsonwebtoken:jjwt-jackson:jar:0.11.5:runtime
[INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.13.5:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.5:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.13.5:compile
[INFO] +- com.stripe:stripe-java:jar:25.13.0:compile
[INFO] +- com.logtail:logback-logtail:jar:0.3.3:compile
[INFO] +- ch.qos.logback:logback-classic:jar:1.2.13:compile
[INFO] +- ch.qos.logback:logback-core:jar:1.2.13:compile
[INFO] +- org.springframework.boot:spring-boot-starter-mail:jar:2.7.14:compile
[INFO] |  \- com.sun.mail:jakarta.mail:jar:1.6.7:compile
[INFO] |     \- com.sun.activation:jakarta.activation:jar:1.2.2:compile
[INFO] +- org.springframework.boot:spring-boot-starter-thymeleaf:jar:2.7.14:compile
[INFO] |  +- org.thymeleaf:thymeleaf-spring5:jar:3.0.15.RELEASE:compile
[INFO] |  |  \- org.thymeleaf:thymeleaf:jar:3.0.15.RELEASE:compile
[INFO] |  |     +- org.attoparser:attoparser:jar:2.0.5.RELEASE:compile
[INFO] |  |     \- org.unbescape:unbescape:jar:1.1.6.RELEASE:compile
[INFO] |  \- org.thymeleaf.extras:thymeleaf-extras-java8time:jar:3.0.4.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-security:jar:2.7.14:compile
[INFO] |  +- org.springframework:spring-aop:jar:5.3.29:compile
[INFO] |  +- org.springframework.security:spring-security-config:jar:5.7.10:compile
[INFO] |  \- org.springframework.security:spring-security-web:jar:5.7.10:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.7.14:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.7.14:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.7.14:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.7.0:compile
[INFO] |  |  \- net.minidev:json-smart:jar:2.4.11:compile
[INFO] |  |     \- net.minidev:accessors-smart:jar:2.4.11:compile
[INFO] |  |        \- org.ow2.asm:asm:jar:9.3:compile
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO] |  +- org.assertj:assertj-core:jar:3.22.0:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.8.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.8.2:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.8.2:test
[INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.8.2:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.8.2:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.8.2:test
[INFO] |  +- org.mockito:mockito-core:jar:4.5.1:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.12.23:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.2:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:4.5.1:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.1:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-core:jar:5.3.29:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.3.29:compile
[INFO] |  +- org.springframework:spring-test:jar:5.3.29:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.9.1:test
[INFO] \- org.springframework.security:spring-security-test:jar:5.7.10:test
[INFO]    \- org.springframework.security:spring-security-core:jar:5.7.10:compile
[INFO]       \- org.springframework.security:spring-security-crypto:jar:5.7.10:compile

```

**Comment by ved-asole** [comment] 2024-12-05 09:21
I just got only 1 record, no GSON library included :

+- com.stripe:stripe-java:jar:25.13.0:compile

**Comment by omkarkulkarni2704** [comment] 2024-12-05 10:30
To resolve the issue, add the GSON dependency to your project's pom.xml file:

<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.10.1</version>
</dependency>

So, Add GSON as a Dependency.

**Comment by seanzhang-stripe** [comment] 2024-12-06 02:35
Hi @ved-asole `gson` is a `runtime` dependency for `stripe-java`, and that's why it's not included in the `compile` dependency list that maven generates. You can refer to the maven artifact [page](https://mvnrepository.com/artifact/com.stripe/stripe-java/25.13.0) for details. 

Therefore, you need to manually include `gson` in your project, this requirement is also mentioned in the README [page](https://github.com/stripe/stripe-java?tab=readme-ov-file#others).

I'll close this ticket because this is the expected behavior. Feel free to re-open it or create a new ticket if you have more questions.

**Closed by seanzhang-stripe** 2024-12-06 02:35 UTC
Labels: bug

**Comment by ved-asole** [comment] 2024-12-06 20:55
Hi @seanzhang-stripe, but can't it be added to the compile time dependency for stripe-java? It is anyhow necessary as the stripe sdk internally uses gson library for parsing all api calls
