### ISSUE TITLE
TaxId Type "unknown" not available

### ISSUE THREAD

**Issue by orangecoding** [stripe/stripe-java#915] opened 2019-12-12 17:52 UTC
After Switching to the latest version 16.2.0, the Customer Tax ID info has changed. I'm using the Customer Builder to build new customer, but when I'm actually very confused about the Types:
https://stripe.com/docs/api/customer_tax_ids/object#tax_id_object-type

However, I'm thinking about setting it to ´unknown` but unfortunately, unknown is not an option that I can chose here...
https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/param/CustomerCreateParams.java#L1124

If I don't know in which country the customer pays taxes, what should I do here?

**Comment by remi-stripe** [comment] 2019-12-12 17:57
@orangecoding You can not set `unknown`. This value can be returned by our API for legacy data but can not be set directly.

You should collect the country of your customer upfront and ensure it's in the list of countries we support!

I'm going to close this out as this is not a bug about the library and instead is a product question. I'd recommend talking to our support team instead about this feature: https://support.stripe.com/contact

**Closed by remi-stripe** 2019-12-12 17:57 UTC
