### ISSUE TITLE
Refunds field always null on webhooks

### ISSUE THREAD

**Issue by Baravd** [stripe/stripe-java#1567] opened 2023-05-23 10:02 UTC
### Describe the bug

Context: We are using the stripe  integration connect implementation with on_behalf_of payments.
We are using the latest java sdk: 22.20.0

When performing a refund, we are adding some metadata: RefundCreateParams refundCreateParams = RefundCreateParams.builder()
                    .setPaymentIntent(pi)
                    .putMetadata('test", "test")
                    
Then on the webhooks side, when receiving an event of type charge.refunded or charge.refund.updated we would like to do some processing based on this metadata, however the charge.refunds field  (of type RefundCollection) is always null. This is especially weird because in the stripe dashboard when checking all the events on the refund of that pi_ the information is present. 
<img width="1302" alt="image" src="https://github.com/stripe/stripe-java/assets/25684388/05693d41-6667-4a55-b5f4-a6275a3d7a07">

### To Reproduce

1. Create a payment intent with a connected account with on_behalf_of
2. Attempt a refund and add metadata to the refund
3. Process charge.refunded event
4. Metadata not present & Charge.refunds is null

### Expected behavior

Metadata should be present on Charge.refunds

### OS

macOS

### Java version

Java 17

### stripe-java version

22.20.0

### API version

2022-11-15

**Comment by remi-stripe** [comment] 2023-05-23 15:23
Hey @Baravd ! Thanks a lot for the detailed report! In the most recent API version [2022-11-15](https://stripe.com/docs/upgrades#2022-11-15) we released the following change:
> [Charge](https://stripe.com/docs/api/charges/object) no longer auto-expands refunds by default. You can [expand the list](https://stripe.com/docs/api#expanding_objects) but for performance reasons we recommended against doing so unless needed.

A side effect of that change means that when a Refund is being created, the only Event being sent is `charge.refunded` which describes a Charge object not a Refund object and that one does not include the `refunds` property. It's something we're aware of and we want to improve this in the future by adding `refund.created` as an official Event type that would be sent for all the Refund creations. Unfortunately we don't have a clear ETA for this just yet but we're working on it.

I'm going to close this issue as this is not a bug about stripe-java itself and is a feature request for the API. You can reach out to our support team to register your interest for this feature: https://support.stripe.com/contact

**Closed by remi-stripe** 2023-05-23 15:23 UTC
Labels: bug
