### ISSUE TITLE
Lot of duplicated class make the library difficult to use

### ISSUE THREAD

**Issue by TheryBaptiste** [stripe/stripe-java#1103] opened 2020-09-15 15:40 UTC
Hello everyone,

I am currently trying to implement this library and I found a lod of duplicated code wich made it not easy to use.

For example the class 
InvoiceItemCreateParams.PriceData
SubscriptionCreateParams.Item.PriceData 

Are basically the same, but are duplicated. Then when using PriceData I also have to duplicate my code.

**Comment by richardm-stripe** [comment] 2020-09-15 16:44
Hi @TheryBaptiste, thanks for the feedback!

This is something we've given some thought to; there are some tradeoffs involved here. In the past we have had more "sharing" of inner structures that have a common shape, but the problem is that as Stripe API changes, sometimes two inner structures that start out with a common shape diverge (one of them gains properties that the other one doesn't), and so we have to take a class that was shared and create two separate classes, which is a breaking change and very inconvenient for users who are trying to update to the latest version of the library, so recently our thinking has been that in these cases it is better that the structures begin unshared, even if this is redundant, rather than to produce unnecessary and confusing breaking changes later on.

I hope that helps you understand why we've made the design choice to duplicate classes. I don't think it's too likely we'll change directions on this, but would you be willing to share some code snippets showing the duplicated code that you would rather not write, so we can see your feedback a little bit more concretely?

**Comment by TheryBaptiste** [comment] 2020-09-15 17:34
Hi @richardm-stripe, first of all thank you for your quick answer.

 Here is the use case,

We first create a "draft invoice" to show the price/discount a customer will be charged if he decide to subscribe.
Then for the object "priceData".
In one case we use it to create an invoice, in the other to create a subscription.

I have to create 2 method, that are basically the same, one for each case

```
private InvoiceItemCreateParams.PriceData generatePriceData() {
        return InvoiceItemCreateParams.PriceData.builder()
            .setCurrency(this.getCurrency())
            .setProduct(this.getPrice().getProduct())
            .setUnitAmountDecimal(BigDecimal.valueOf(this.getAmount()))
            .build();
    }


    private SubscriptionCreateParams.Item.PriceData generatePriceDataSub() {
        return SubscriptionCreateParams.Item.PriceData.builder()
            .setCurrency(this.getCurrency())
            .setProduct(this.getPrice().getProduct())
            .setUnitAmountDecimal(BigDecimal.valueOf(this.getAmount()))
            .build();
    }
```

I can't find a way to avoid duplication without a parent class for "PriceData" (or using Reflection which is not recommended)

PS: I have a lot of similare snipet code between subscription and invoice

**Comment by richardm-stripe** [comment] 2020-09-15 18:13
Thanks @TheryBaptiste, seeing the code helps. I don't see a way to reduce duplication either, there's a way in Java we can both remove the redundancy and avoid the eventuality of breaking changes if the two types were to diverge.

I'm closing this issue because we're not prepared to make a change along these lines, but thank you again for the feedback and discussion!

**Closed by richardm-stripe** 2020-09-15 18:13 UTC
