### ISSUE TITLE
GSON warning on jdk-14

### ISSUE THREAD

**Issue by tombryden** [stripe/stripe-java#1105] opened 2020-09-21 11:39 UTC
Hi,

When using methods such as `Customer.retrieve()` and `cust.toJson()` a warning is printed to console from GSON lib:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.reflect.UnsafeReflectionAccessor (file:/C:/Users/Tom/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar) to constructor java.net.Proxy()
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.UnsafeReflectionAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Seems like this issue will cause serious fault down the line if unfixed.

Thanks

**Comment by MrInterBugs** [comment] 2021-03-18 21:00
To add that it also seems to be happening somewhere in this code using JDK 15: 

```try {
        PaymentIntentCreateParams createParams = new PaymentIntentCreateParams.Builder()
            .setCurrency("gbp")
            .setAmount(amount)
            .setReceiptEmail(email)
            .setDescription("Blah blah")
            .build();

        PaymentIntent intent = PaymentIntent.create(createParams);
        CreatePaymentResponse paymentResponse = new CreatePaymentResponse(intent.getClientSecret());```

Switch to JDK 11 and it disapears.

**Comment by unsavorypeople** [comment] 2021-04-09 23:41
It looks like this issue finally surfaced fully in JDK 16:  https://github.com/stripe/stripe-java/issues/1190

Will there be a fix for this soon?

**Comment by dcr-stripe** [comment] 2022-06-28 14:50
Going to close this out as a duplicate of https://github.com/stripe/stripe-java/issues/1190 which has now been fixed.

Please feel free to re-open if you are still experiencing issues!

**Closed by dcr-stripe** 2022-06-28 14:50 UTC
