### ISSUE TITLE
Null PaymentIntentObject when used with Coupon

### ISSUE THREAD

**Issue by PopTudor** [stripe/stripe-java#1146] opened 2020-11-01 17:42 UTC
Java 11
Stripe SDK 19.45.0
if I attach a PromoCode/Coupon to a subscription or if a Customer has attached a coupon/promo code then I create a subscription using PaymentIntent API it returns `null` when calling `subscription.getLatestInvoiceObject().getPaymentIntentObject();`
I've read in the docs that `Coupon` doesn't work with `PaymentIntent` but at least the SDK should give you a warning instead of returning null

**Comment by remi-stripe** [comment] 2020-11-01 18:03
@PopTudor The latest invoice only has a PaymentIntent associated with it if the invoice was not for $0. What is likely happening here is that the first month is free because of the Coupon and so there's no PaymentIntent, which is expected.

I'm going to close this issue as it's not a bug with the stripe-java library and more a questions about the product/API. I'd recommend following up with our support team if you have more questions: https://support.stripe.com/contact

**Closed by remi-stripe** 2020-11-01 18:03 UTC
