### ISSUE TITLE
Consolidate GSON configurations in a recursion-friendly way

### ISSUE THREAD

**Issue by brandur-stripe** [stripe/stripe-java#433] opened 2017-12-06 22:07 UTC
As mentioned in #432, it's a problem that each of our deserializer classes (e.g. `ChargeRefundCollectionDeserializer`) creates its own GSON instance because it leaves the door open to forgetting to register certain type adapters that are included in `APIResource.GSON`. Currently we have this working optimistically so that hopefully any type adapters needed by any particular deserializer will be configured there.

Ideally, type adapters should all be registered in one place. Using `APIResource.GSON` has been a problem because if used from a deserializer, it will cause issues with recursion.

I'm not sure what the right answer for this is off hand, but GSON is a really big library with lots of usage, so there must be a better way to do this.

**Comment by codylerum** [comment] 2018-01-04 03:06
@brandur-stripe I took a glace at this and I don't see a path where you can get to having a single GSON instance without changing the hierarchy.

The issue comes down to using GSON to deserialize the same type as the deserializer 

https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/ChargeRefundCollectionDeserializer.java#L38

So currently you need to have a second instance of GSON which does not register the adapter for the specific type the deserializer is typed to. If you do then it just loops and stack-overflows.

So you need to have two different types for ChargeRefundCollection. Something like:

ChargeRefundCollectionAsArray
ChargeRefundCollectionAsObject

**Comment by ob-stripe** [comment] 2019-04-10 16:05
I'm closing this issue: the root cause described here hasn't been fixed, but as of stripe-java v8.0.0, the library is pinned to a specific API version. As a result, we were able to drop most of the custom deserializers that we used to have to handle the changes caused by different API versions, and so the problem is mostly gone.

**Closed by ob-stripe** 2019-04-10 16:05 UTC
