### ISSUE TITLE
Issue with setUnitAmountDecimal and supported decimal places

### ISSUE THREAD

**Issue by josh-s-g** [stripe/stripe-java#1050] opened 2020-06-24 10:04 UTC
When creating a Checkout session with `PriceData` I can't seem to use `setUnitAmountDecimal` with decimal places. E.g.

```scala
      val price = BigDecimal(1000.99).bigDecimal.setScale(2) // creates a java.math.BigDecimal

      // Building on the example in the docs:
      SessionCreateParams.builder()
        .addPaymentMethodType(SessionCreateParams.PaymentMethodType.CARD)
        .addLineItem(
          SessionCreateParams.LineItem.builder()
            .setPriceData(
              PriceData.builder()
                .setCurrency("GBP")
                .setProduct("prod_abc123")
                .setUnitAmountDecimal(price)
                .build()
            )
            .setQuantity(1L)
            .build()
        )
        .setMode(SessionCreateParams.Mode.PAYMENT)
        .setSuccessUrl("https://example.com/success?session_id={CHECKOUT_SESSION_ID}")
        .setCancelUrl("https://example.com/cancel")
        .build();
```
compiles fine, but returns an exception when run: 

```
Checkout does not support plans with more than 2 decimals in the `amount` in `line_items[0]`.; request-id: req_abc123
```

presumably I'm doing something wrong with `setPriceData`? 

I'm using Scala 2.12 and the Stripe Java SDK v19.24.0

**Comment by remi-stripe** [comment] 2020-06-25 02:17
@josh-s-g Thanks for reaching out. At the moment, Checkout doesn't support prices with more than 2 decimals which is why you are getting this error.

Remember that the amount is in the smallest currency unit so `unit_amount_decimal: "1000.99"` means £10.0099  and not £1000.99. If you want to charge £1000.99 you can simply pass `unit_amount: 100099` instead!

I'm going to close this issue as it's not a bug with the stripe-java library. It's either a limitation of Checkout or confusion on how the amount parameter works.

**Closed by remi-stripe** 2020-06-25 02:17 UTC
