### ISSUE TITLE
Ability to create ExternalAccount using AccountCreateParams

### ISSUE THREAD

**Issue by qlereboursBS** [stripe/stripe-java#1368] opened 2022-06-03 11:38 UTC
### Is your feature request related to a problem? Please describe.

Currently, on the [Java documentation](https://stripe.com/docs/api/accounts/create) we can see that the `external_account` parameter can be passed if we use the `create` method with the Map: `public static Account create(Map<String, Object> params)`.

However, when using the `create` method that uses the `AccountCreateParams`, (`public static Account create(AccountCreateParams params)`), we can't because the `AccountCreateParams` accepts only a string as for the `setExternalAccount` method.

### Describe the solution you'd like

I'd like to be able to create an Account along with the ExternalAccount in a single call, instead of having to create the ExternalAccount first, and call the `Account.create()` method with an external account identifier in the `CreateAccountParams.setExternalAccount` method

**Comment by qlereboursBS** [comment] 2022-06-03 11:50
Sorry, I think I just noticed that the string is not the external account identifier but a token, which would mean that you probably restricted this behavior because creating account is authorized only using a token (like [bank account token](https://stripe.com/docs/api/tokens/create_bank_account)). However, the documentation doesn't seem to be up to date with this.

**Comment by remi-stripe** [comment] 2022-06-03 22:45
@qlereboursBS The documentation should be up to date but we only support the string today in the client libraries. Too many developers misunderstand the flow and try to pass raw card details server-side when they should be collecting those client-side instead. The API does support passing the raw card (undocumented) and raw bank account details but we don't support this in the library itself.

I'm going to close this out as it's not a bug with the library, I hope it's okay!

**Closed by remi-stripe** 2022-06-03 22:45 UTC
Labels: feature-request

**Comment by qlereboursBS** [comment] 2022-06-06 09:31
I understand, Thanks for answering
