### ISSUE TITLE
Attribute `documents` is not present in `com.stripe.model.Account`

### ISSUE THREAD

**Issue by sardortaylakov** [stripe/stripe-java#1262] opened 2021-09-13 18:03 UTC
Hi, we are creating a file to provide company registration verification during account update. We set the file id in in the documents property per [this]( https://stripe.com/docs/api/accounts/update#update_account-documents) doc. However, there is no documents property under `com.stripe.model.Account` for us to retrieve the document after uploading it. Can this property be added? (Also needs to be reflected in [this](https://stripe.com/docs/api/accounts/object) doc).

**Comment by remi-stripe** [comment] 2021-09-13 18:24
@sardortaylakov This is expected behaviour today. This information is "write only" today and never returned back in the API. We use this for you to provide a specific copy of the doc we need and store it internally but we won't return this.

I'm going to close this out as it's more an API design feature request and not a bug with stripe-java and it's not something we plan to add for now. You can raise this feedback directly with the support team though: https://support.stripe.com/contact

**Closed by remi-stripe** 2021-09-13 18:24 UTC
