### ISSUE TITLE
Subscription Unknown TaxRate error

### ISSUE THREAD

**Issue by FV-Valraiso** [stripe/stripe-java#793] opened 2019-06-21 07:38 UTC
Hi,

I'm on version 10.0.2
I receive this error, when I specify a "default_taxe_rate" on a subscription :
```
com.stripe.exception.InvalidRequestException: No such taxrate: <com.stripe.model.TaxRate@1964303080 id=txr_1EngzDGFTI9BonEckNfARG4n> JSON: {
  "active": true,
  "created": 1561101399,
  "description": "VAT France",
  "display_name": "VAT",
  "id": "txr_1EngzDGFTI9BonEckNfARG4n",
  "inclusive": true,
  "jurisdiction": "FR",
  "livemode": false,
  "metadata": {},
  "object": "tax_rate",
  "percentage": 0.2
};
```

```
Map<String, Object> subscriptionParams = new HashMap<>(2);
subscriptionParams.put("customer", customerId);
subscriptionParams.put("items", subscriptionItemsParams);
if (taxId != null) {
    TaxRate taxRate = TaxRate.retrieve(taxId);
    List<TaxRate> taxes = new ArrayList<>(1);
    taxes.add(taxRate);
    subscriptionParams.put("default_tax_rates", taxes);
}

Subscription.create(subscriptionParams);
```
I just loaded my TaxRate `TaxRate taxRate = TaxRate.retrieve(taxId);` and I checked `"txr_1EngzDGFTI9BonEckNfARG4n"` exists.
I'm in test mode so `"livemode": false` is normal.
If I remove `subscriptionParams.put("default_tax_rates", taxes);` it creates the subscription.

Thanks for help
Francis

**Comment by ob-stripe** [comment] 2019-06-21 07:55
Hi @FV-Valraiso,

When preparing the list of tax rates, you need to pass the tax rate ID, not the full object. This should work:
```java
if (taxId != null) {
    List<String> taxes = new ArrayList<>(1);
    taxes.add(taxId);
    subscriptionParams.put("default_tax_rates", taxes);
}
```

Note that the library now also supports fully typed parameters instead of untyped maps:
```java
SubscriptionCreateParams.Builder subscriptionParamsBuilder = SubscriptionCreateParams.builder()
  .setCustomer(customerId)
  .setItems(subscriptionItemParams);
if (taxId != null) {
  List<String> taxRates = new ArrayList<>(1);
  taxRates.add(taxId);
  subscriptionParamsBuilder.setDefaultTaxRates(taxRates);
}
SubscriptionCreateParams subscriptionParams = subscriptionParamsBuilder.build();
Subscription.create(subscriptionParams);
```

With typed parameters, you would have caught the issue at compile time because `setDefaultTaxRates` only accepts a `List<String>`, not a `List<TaxRate>`.

Hope this helps! I'm closing the issue since this is not a bug with the library, but feel free to reply.

**Closed by ob-stripe** 2019-06-21 07:55 UTC

**Comment by FV-Valraiso** [comment] 2019-06-21 07:58
Great thanks, it works.
The documentation is not really clear about default_tax_rates and no example is provided.

Thanks again

**Comment by ob-stripe** [comment] 2019-06-21 08:02
Ah yes, just saw that we only have curl examples on https://stripe.com/docs/billing/invoices/tax-rates. We'll update those to show how to use tax rates with our client libraries. Thanks for the feedback!
